### ISSUE TITLE
line_of_sight.py doesn't calculate correct x,y,z start and end positions.

### ISSUE THREAD

**Issue by gadgil48** [ukaea/Indica#108]
**Describe the bug**
`indica/converters/line_of_sight.py` doesn't calculate correct x, y, z start and end positions given origin and direction info.

**Minimal Reproducer**
Initialise `LinesOfSightTransform` in `indica/converters/line_of_sight.py` with:
`origin_x = 3.3276`,
`origin_y = 0.0`,
`origin_z = 1.6921`,
`direction_x = 0.150442918958628`,
`direction_y = 0.0`,
`direction_z = -0.9886186970390595`,
`name="testLoS"`

The calculated start and end positions are: 
`x_start = 3.9`,
`y_start = 0.0`,
`z_start = 1.6921`,
`x_end = 1.83`,
`y_end = 0.0`,
`z_end = 1.6921`

**Expected behavior**
The `x_start`, `y_start`, `z_start` and `x_end`, `y_end`, `z_end` after initialisation should be:
`x_start = 3.3276`,
`y_start = 0.0`,
`z_start = 1.621`,
`x_end = 3.8514`,
`y_end = 0.0`,
`z_end = -1.75`

**Additional context**
I'm pretty sure the problem is in the `_find_wall_intersections` function where there are a few things that look incorrect. For example, `z_start = origin[-1]` and `z_end = origin[-1]` (both `z_start` and `z_end` are defined as `origin_z`). Additionally I'm not sure I see the point of redefining `x_start` and `y_start` given the location of the instrument should be fixed in space.

**Comment by jmwood94-0** [comment]
@gadgil48 

I've just had a look and indeed you are right to point out the problem with the start coordinates - I don't really know why I had done it this way, I should just use the provided start points instead of calculating them in the wall intersections function. 

Will also make an update on calculating vertical coordinate in the lines of sight as well - this may be a little more complicated and take more time but there are ways to do this. 

I'll work on this example once I have completed a small pull request for Marco https://github.com/ukaea/Indica/pull/109 . Then will open a new branch for this issue.

**Comment by jmwood94-0** [comment]
Modified the line of sight transform to work in the vertical domain. And changes the origin position to be the x_start, y_start and z_start points in the class. 

New results for same inputs:
x_start = 3.3276,
y_start = 0.0,
z_start = 1.621,
x_end = 3.8514,
y_end = 0.0,
z_end = -1.75

The LOS will stop at the Z limits if it hasn't intersected the wall beforehand. 

Other tests working as expected. 

Opening a pull request
