### ISSUE TITLE
Complete xyz conversion

### ISSUE THREAD

**Issue by marcosertoli** [ukaea/Indica#82]
**Describe the bug**
Conversion from R,z,T to x,y,z in lines_of_sight was incomplete, with order of variables still in original state and a few methods that needed fixing

**Proposed solution**
I've modified the master version and pushed it to  marcosertoli/64_rename_LoS_coords. This mod will require changes to all the calls of lines_of_sight and anything related to it in abstractreader and ppfreader. I've already modified my local st40 version (marcosertoli/st40 branch) that can be taken as example.

This is long due and the sooner we're done with it, the less modifications will have to be done to other parts of the code

**Additional features**
@jmwood94-0 is working on new mods to lines_of_sight.py to calculate intersections with inner column and define the LOS from these intersections + the desired spatial resolution, not from the number of points.
This will also require that different LOS of the same diagnostic each have its own transform instead of one transform for the whole diagnostic as it is now.

**Proposal on how to tackle mods**
@jmwood94-0 to modify the lines_of_sight for wall intersections and dl calculation
@gadgil48 to modify the abstractreader and ppfreader to be consistent with new xyz coordinates

**Comment by jmwood94-0** [comment]
Actions from meeting with Ed and Sanket on 11/03/22:

- Line of sight transform will be a Dataset variable, where Dataset = {value, error, transform}. The transform will be a DataArray of line of sight transforms. The benefit being that the user can select the channel which they are interested in, and only one transform is returned. 
- This update requires the line of sight transform to take only one channel, where x_start, y_start, z_start, x_end, y_end and z_end are single values. 
- The number of points (set via the distance between 2 coordinates along the line of sight) is a new input to the class, called "dell". 
- The intersection between the line of sight and the IVC (or centre column) sets the start and end coordinates in the class.  
- Update the name of the class to "LineOfSightTransform" instead of "LinesOfSightTransform" -> since only accepts one line of sight (channel). 
- Class takes in origin and direction vectors instead of the start and end coordinates. More general. 
- Keeping all the class variables (including x_start etc..).

Comments on knock on impacts of the change:

- Shouldn't be too difficult to update Indica to allow for this change. 
- Need to update some codes that make use of the lines of sight transform (including Bolometry, Sanket). 
- Agreed to document on git issue #82 and meet again on 16/03/22.

Marco requests:

- Make the origin and direction vectors Tuple instead of numpy arrays. 
- Inside the line of sight transform, add a method where the user provides the FluxSurfaceCoordinate class and calculates the rho coordinate along the defined line of sight. Accessible from transform.rho. 
- Add x, y, z, r and theta (coordinates along the line of sight) as a class variable.

Update (14/03/22):

- Added new branch called jmwood94-0/82_line_of_sight_transform to develop the class https://github.com/ukaea/Indica/tree/jmwood94-0/82_line_of_sight_transform. 
- Updated function to take origin and direction vectors as Tuple's. 
- Updated function to calculate the start and end coordinates from the IVC wall and centre column information (machine_dimensions). 
- Updated function to calculate "x2" with a optional input "dell", which is the distance between adjacent coordinates along the line of sight. 
- Updated function to include "x", "y", "z", "r", "theta" variables which store the coordinates along the line of sight.

**Comment by jmwood94-0** [comment]
Update (15/03/22):

- Added function for assigning flux transform (FluxSurfaceCoordinates) to the LinesOfSightTransform class called "assign_flux_transform". Returned as a new class variable "flux_transform".
- Added function for converting line of sight coordinates to rho via the FluxSurfaceCoordinates class. Returned as a new class variable "rho".
- Tested for an ST40 equilibrium and appears to be working!

Next, check other methods inside LinesOfSightTransform are all working: 1. "convert_to_Rz", 2. "convert_from_Rz" and 3. "distance"

**Comment by jmwood94-0** [comment]
Update (18/03/22):

- Updated inputs to be "origin_x", "origin_y", "origin_z", "direction_x", "direction_y", "direction_z" as a float. Instead of Tuples. 
- Changed "self.r" to "self.R" for correct Physics notation. 
- Decided to keep "R" as a class variable, this is to save time if/when we do iterative optimisations. Preference to calculate x, y, z, R once. 
- Deleted commented code and unused functions, including _get_wall_intersection_distances. 
- Replaced test script in tests/unit/converters with new class. 2 test functions called "convert_to_rho" and "test_methods". Working locally. 

Next step: Pull request

**Comment by jmwood94-0** [comment]
Reopen issue to update line_of_sight transform in 2 ways: (1) change convert_to_xyz to convert_to_xy so that the tuple is always 2 (Marco request), the Z dimensions can be accessed by convert_to_Rz, (2) change the variables self.x1_name and self.x2_name to "channel" and "los_position" respectively. 

The test script needs updating as well!

**Comment by jmwood94-0** [comment]
Accidentally closed git issue before pull request complete!
